title: Ramblings of an Alchemist
author: Riven Skaye
url: https://skaye.blog
description: Blog of someone doing pseudo-arcane things on computers.
permalink: /:categories/:slug
destination: docs/
exclude: [_config.yml]
include: [LICENSE-MIT, LICENSE-MPL]
timezone: Europe/Amsterdam
encoding: utf-8
remote-theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "Back to Home"
  date_format: "%F"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: true
  show_old_projects: false
  show_misc_list: false
  show_reading_time: false
  show_tags: true
  home:
    title_about: About
    title_blog: Recent Ramblings

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  excerpt_only: true
  posts_limit: 42
  tags:
    except:
      - windows
      - shared-mem
      - intro

    path: "/feed/"

ignored_tags:
  - windows
  - shared-mem
  - intro
#  - winmmf
#  - rust
#  - tech
#  - personal
#  - alice
#  - irl
